CREATE TABLE STORE(
  STORE_NAME 	VARCHAR(50),
  STORE_ID 	CHAR(10),
  ADDRESS 	VARCHAR(50),
  PRIMARY KEY(STORE_NAME, STORE_ID)
  #probably need to make address have multiple attributes
);

CREATE TABLE CUSTOMER(
  CID CHAR(10),
  STORE_NAME VARCHAR(50),
  STORE_ID CHAR(10),
  CUST_NAME VARCHAR(50),
  PHONE CHAR(10),
  PRIMARY KEY(CID, STORE_NAME, STORE_ID),
  FOREIGN KEY(STORE_NAME, STORE_ID) REFERENCES STORE(STORE_NAME, STORE_ID)
);

CREATE TABLE CUST_ADDRESS(
  CID CHAR(10) REFERENCES CUSTOMER(CID),
  STORE_NAME VARCHAR(50) REFERENCES STORE(STORE_NAME),
  STORE_ID CHAR(10)REFERENCES STORE(STORE_ID),
  STREET VARCHAR(15),
  CITY VARCHAR(15),
  STATE CHAR(2),
  ZIP CHAR(5),
  FOREIGN KEY(CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (STORE_NAME, STORE_ID) REFERENCES STORE(STORE_NAME, STORE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

# IN THIS TABLE, SHOULD CID BE A FOREIGN KEY LINKED TO THE OTHER TABLE?
CREATE TABLE ORDERS(
  ORDER_ID CHAR(10) PRIMARY KEY,
  CID CHAR(10) REFERENCES CUSTOMER(CID),
  PRODUCT VARCHAR(10)
);

CREATE TABLE BOXES(
  BOX_ID CHAR(10) PRIMARY KEY,
  BOX_TYPE VARCHAR(10)
);

CREATE TABLE STORE_DRIVER(
  STORE_ID	CHAR(10),
  EMP_ID CHAR(10),
  PRIMARY KEY(STORE_ID, EMP_ID),
  FOREIGN KEY(STORE_ID) REFERENCES STORE (STORE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE BIG_DRIVER(
  EMP_ID CHAR(10) PRIMARY KEY,
  RADIUS INT, #change to select store
  DRIVER_NAME VARCHAR(50),
  NO_BOXES INT,
  BOX_CAPACITY INT,
  SALARY INT,
  FOREIGN KEY(EMP_ID) REFERENCES STORE_DRIVER(EMP_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SMALL_DRIVER(
  EMP_ID CHAR(10) PRIMARY KEY,
  RADIUS INT, #change to select store
  DRIVER_NAME VARCHAR(50),
  NO_BOXES INT,
  BOX_CAPACITY INT,
  HOURLY_WAGE INT,
  FOREIGN KEY(EMP_ID) REFERENCES STORE_DRIVER(EMP_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DRIVER_ORDER(
  EMP_ID CHAR(10),
  ORDER_ID CHAR(10),
  PRIMARY KEY (EMP_ID, ORDER_ID),
  FOREIGN KEY(EMP_ID) REFERENCES STORE_DRIVER(EMP_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SHIPS(
  BOX_ID CHAR(10),
  EMP_ID CHAR(10),
  EST_DEL TIMESTAMP,
  ACT_DEL TIMESTAMP,
  PRIMARY KEY(BOX_ID, EMP_ID),
  FOREIGN KEY(BOX_ID) REFERENCES BOXES(BOX_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(EMP_ID) REFERENCES STORE_DRIVER(EMP_ID) ON UPDATE CASCADE ON DELETE CASCADE
);